"""2st migrations

Revision ID: 9f7b7da6188d
Revises: 21e2c14fee8f
Create Date: 2025-03-28 20:25:52.450566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f7b7da6188d'
down_revision: Union[str, None] = '21e2c14fee8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['uid'])
    op.create_unique_constraint(None, 'items', ['uid'])
    op.create_unique_constraint(None, 'purchas_items', ['uid'])
    op.create_unique_constraint(None, 'purchase', ['uid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'purchase', type_='unique')
    op.drop_constraint(None, 'purchas_items', type_='unique')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
